version: '3.8'

services:
  tweego-database:
    container_name: tweego-database
    build:
      context: ./build/db
      dockerfile: Dockerfile.dev
    volumes:
      - tweego-database-data:/var/lib/postgresql/data:cached
    environment:
      POSTGRES_PASSWORD: "Passw0rd"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
      POSTGRES_USER: "webapp"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 10

  tweego-api:
    container_name: tweego-api
    platform: linux/amd64
    build:
      context: ./build/app
      dockerfile: Dockerfile.dev
    depends_on:
      tweego-database:
        condition: service_healthy
    ports:
      - '80:80'
    env_file:
      - ./build/.go_env
    tty: true
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./tweego-api:/go/app:cached

volumes:
  tweego-database-data:
    name: tweego-database-data
    external: true
